apiVersion: skaffold/v4beta1
kind: Config
build:
  artifacts:
  - image: gcr.io/ticketing-dev-375021/auth
    context: auth
    sync:
      manual:
      - src: src/**/*.ts
        dest: .
    docker:
      dockerfile: Dockerfile
  googleCloudBuild:
    projectId: ticketing-dev-375021
manifests:
  rawYaml:
  - ./infra/k8s/*
deploy:
  kubectl: {}
